### ISSUE TITLE
How to make a custom call to a smart contract? (non-standard)

### ISSUE THREAD

**Issue by waterlink** [Tangany/waas-js-sdk#19]
I see that there is basic ERC20 support here, but how do I call a custom method that I have on my smart contract?

**Comment by kepikoi** [comment]
Currently you can call arbitrary smart contract methods by utilizing the `data` field in a ethereum wallet transaction call.

**Example:** 

HTTP api:
```http
POST https://api.tangany.com/v1/eth/wallet/{wallet}/send
Content-Type: application/json

{
  "to": "0xc32ae45504ee9482db99cfa21066a59e877bc0e6",
  "amount": "0",
  "data": "0x40c10f1900000000000000000000000076f0ce0ee55bf1aae0adf85a2cd348b8dd3583760000000000000000000000000000000000000000000000000de0b6b3a7640000"
}

###
```
The same call via the Javascript SDK:

```javascript
const { hash } = await api.wallet(wallet).eth().send({
    to: "0xc32ae45504ee9482db99cfa21066a59e877bc0e6",
    amount: "0",
    data: "0x40c10f1900000000000000000000000076f0ce0ee55bf1aae0adf85a2cd348b8dd3583760000000000000000000000000000000000000000000000000de0b6b3a7640000" // mint 1 token to 0x76f0ce0ee55bf1aae0adf85a2cd348b8dd358376
});
```

Here I'm executing the `mint` method on the `0xc32ae45504ee9482db99cfa21066a59e877bc0e6` token using following arguments: `to=0x76f0ce0ee55bf1aae0adf85a2cd348b8dd358376, amount=1000000000000000000`. 

You can verify the input data on this exact transaction on etherscan: https://ropsten.etherscan.io/tx/0x26d4266d5390a04889c980fd9ce11092e0841ef285eb3c6a6e3de1623bc4e30c

To build a valid `data` string, it is required to know the ABI interface of the target smart contract method. Then you could e.g. use the [`web3` library](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-abi.html#encodefunctioncall) to construct the desired payload:

```javascript
const Web3 = require("web3");
const abi = {
    name: 'mint',
    type: 'function',
    "inputs": [
        {
            "name": "_to",
            "type": "address"
        },
        {
            "name": "_amount",
            "type": "uint256"
        }
    ],
};

const data = new Web3().eth.abi.encodeFunctionCall(abi, ["0x76f0ce0ee55bf1aae0adf85a2cd348b8dd358376", "1000000000000000000"]);

console.log(data);
// 0x40c10f1900000000000000000000000076f0ce0ee55bf1aae0adf85a2cd348b8dd3583760000000000000000000000000000000000000000000000000de0b6b3a7640000
```

We are also working on a new, improved interface for smart contract interactions and will introduce it shortly.

**Comment by waterlink** [comment]
@kepikoi Thank you! That’s exactly what I was looking for. And we’re all looking forward to this new interface too!

**Comment by kepikoi** [comment]
@waterlink I'm glad! I will then proceed and close this issue. Feel free to comment for further assistance
