### ISSUE TITLE
Unable to provide a custom `Tangany-Etherium-Network` header

### ISSUE THREAD

**Issue by waterlink** [Tangany/waas-js-sdk#20]
Right now, in the documentation (both in this SDK library’s README, and on the API doc [here](https://tangany.docs.stoplight.io/api/ethereum/get-eth-balance)), I can see it should be possible to provide a private URL of the private blockchain RPC server (for testing purposes).

The header seems to be called `Tangany-Ethereum-Network`, but when I provide it (in this SDK, or directly through an API call via `curl`), I still get a response from `ropsten`.

Is that how it supposed to work or not?

**Comment by kepikoi** [comment]
Calling an ethereum endpoint without the network header defaults to the ethereum _mainnet_. You can pass the URL for you private ethereum network via the `tangany-ethereum-network` header e.g. `http://myethnw.mysamplehost.com:8545` and verify it against the response header

![image](https://user-images.githubusercontent.com/12378498/78161018-20cb9600-7445-11ea-8652-06aa39b3e8a3.png)

In the JS SDK you can set `ethereumNetwork` in the constructor argument to achieve the same

```js
new Waas({
        ethereumNetwork: "http://myethnw.mysamplehost.com:8545",
        ...options
    })
```

**Comment by waterlink** [comment]
This is what I have done. I’ve tried setting `etheriumNetwork: "http://my.domain:80"` and I’ve seen that it is still reading from `ropsten` network.

Then I tried to use the “test request” feature from the [docs page](https://tangany.docs.stoplight.io/api/ethereum/get-eth-balance) and provided `tangany-etherium-network` value. The response came back from `ropsten` again.

For context: I was trying to do that on a “demo” tangany account (not on production one). Could it be that “demo” account always uses `ropsten` no matter what’s provided in the header? (or doesn’t allow custom private endpoint?)

**Comment by kepikoi** [comment]
Yes, that's is the culprit. Demo accounts are not allowed to access private networks and default to ropsten

**Comment by waterlink** [comment]
Thanks!

**Comment by waterlink** [comment]
BTW, just an idea to consider: there is a cool opportunity here to provide an API warning in a special header in this scenario. Something like:

```
Tangany-Warning: Demo accounts cannot use mainnet or private networks. Using ropsten, instead.
```

**Comment by kepikoi** [comment]
Thanks, we will consider it
